### ISSUE TITLE
Do not see opened positions on Umbrel

### ISSUE THREAD

**Issue by TomaszWaszczyk** [ln-markets/umbrel#31]
**Describe the bug**
I have installed LNMarkets on Umbrel and I do not see opended positions:

![image](https://user-images.githubusercontent.com/1605705/154134794-c5fa4f6b-efc8-409a-8a6b-b478368302a6.png)

**Comment by RomainRouphael** [comment]
Hey, thanks for reporting! 
We did a fix, still having this issue with Umbrel / LNM App last version?

**Comment by TomaszWaszczyk** [comment]
It works!!
